# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: 'Run Gemini CLI'
author: 'Google LLC'
description: |-
  Invoke the Gemini CLI from a GitHub Action.

inputs:
  gcp_location:
    description: 'The Google Cloud location.'
    required: false
  gcp_project_id:
    description: 'The Google Cloud project ID.'
    required: false
  gcp_service_account:
    description: 'The Google Cloud service account email.'
    required: false
  gcp_workload_identity_provider:
    description: 'The Google Cloud Workload Identity Provider.'
    required: false
  gcp_token_format:
    description: 'The token format for authentication. Set to "access_token" to generate access tokens (requires service account), or set to empty string for direct WIF. Can be "access_token" or "id_token".'
    required: false
    default: 'access_token'
  gcp_access_token_scopes:
    description: 'The access token scopes when using token_format "access_token". Comma-separated list of OAuth 2.0 scopes.'
    required: false
    default: 'https://www.googleapis.com/auth/cloud-platform,https://www.googleapis.com/auth/userinfo.email,https://www.googleapis.com/auth/userinfo.profile'
  gemini_api_key:
    description: 'The API key for the Gemini API.'
    required: false
  gemini_cli_version:
    description: 'The version of the Gemini CLI to install. Can be "latest", "preview", "nightly", a specific version number, or a git branch, tag, or commit. For more information, see [Gemini CLI releases](https://github.com/google-gemini/gemini-cli/blob/main/docs/releases.md).'
    required: false
    default: 'latest'
  gemini_debug:
    description: 'Enable debug logging and output streaming.'
    required: false
  gemini_model:
    description: 'The model to use with Gemini.'
    required: false
  google_api_key:
    description: 'The Vertex AI API key to use with Gemini.'
    required: false
  prompt:
    description: |-
      A string passed to the Gemini CLI's [`--prompt` argument](https://github.com/google-gemini/gemini-cli/blob/main/docs/cli/configuration.md#command-line-arguments).
    required: false
    default: 'You are a helpful assistant.'
  settings:
    description: |-
      A JSON string written to `.gemini/settings.json` to configure the CLI's _project_ settings.
      For more details, see the documentation on [settings files](https://github.com/google-gemini/gemini-cli/blob/main/docs/cli/configuration.md#settings-files).
    required: false
  use_gemini_code_assist:
    description: |-
      Whether to use Code Assist for Gemini model access instead of the default Gemini API key.
      For more information, see the [Gemini CLI documentation](https://github.com/google-gemini/gemini-cli/blob/main/docs/cli/authentication.md).
    required: false
    default: 'false'
  use_vertex_ai:
    description: |-
      Whether to use Vertex AI for Gemini model access instead of the default Gemini API key.
      For more information, see the [Gemini CLI documentation](https://github.com/google-gemini/gemini-cli/blob/main/docs/cli/authentication.md).
    required: false
    default: 'false'
  extensions:
    description: 'A list of Gemini CLI extensions to install.'
    required: false
  upload_artifacts:
    description: 'Whether to upload artifacts to the github action.'
    required: false
    default: 'false'
  use_pnpm:
    description: 'Whether or not to use pnpm instead of npm to install gemini-cli'
    required: false
    default: 'false'
  workflow_name:
    description: 'The GitHub workflow name, used for telemetry purposes.'
    required: false
    default: '${{ github.workflow }}'

outputs:
  summary:
    description: 'The summarized output from the Gemini CLI execution.'
    value: '${{ steps.gemini_run.outputs.gemini_response }}'
  error:
    description: 'The error output from the Gemini CLI execution, if any.'
    value: '${{ steps.gemini_run.outputs.gemini_errors }}'

runs:
  using: 'composite'
  steps:
    - name: 'Validate Inputs'
      id: 'validate_inputs'
      shell: 'bash'
      run: "$GITHUB_ACTION_PATH/scripts/validate_inputs.sh"
      env:
        INPUT_GEMINI_API_KEY_PRESENT: "${{ inputs.gemini_api_key != '' }}"
        INPUT_GOOGLE_API_KEY_PRESENT: "${{ inputs.google_api_key != '' }}"
        INPUT_GCP_WORKLOAD_IDENTITY_PROVIDER_PRESENT: "${{ inputs.gcp_workload_identity_provider != '' }}"
        INPUT_GCP_PROJECT_ID_PRESENT: "${{ inputs.gcp_project_id != '' }}"
        INPUT_GCP_SERVICE_ACCOUNT_PRESENT: "${{ inputs.gcp_service_account != '' }}"
        INPUT_GCP_TOKEN_FORMAT: '${{ inputs.gcp_token_format }}'
        INPUT_USE_VERTEX_AI: '${{ inputs.use_vertex_ai }}'
        INPUT_USE_GEMINI_CODE_ASSIST: '${{ inputs.use_gemini_code_assist }}'

    - name: 'Sanitize workflow name'
      id: 'sanitize_workflow_name'
      shell: 'bash'
      run: |
        SANITIZED=$(echo "${WORKFLOW_NAME}" | sed 's/[^ a-zA-Z0-9-]//g' | xargs | tr ' ' '_' | tr '[:upper:]' '[:lower:]')
        echo "gh_workflow_name=$SANITIZED" >> $GITHUB_OUTPUT
      env:
        WORKFLOW_NAME: '${{ inputs.workflow_name }}'

    - name: 'Configure Gemini CLI'
      if: |-
        ${{ inputs.settings != '' }}
      run: |-
        mkdir -p .gemini/
        echo "${SETTINGS}" > ".gemini/settings.json"
      shell: 'bash'
      env:
        SETTINGS: '${{ inputs.settings }}'

    - name: 'Install Custom Commands'
      shell: 'bash'
      run: |-
        set -euo pipefail
        mkdir -p .gemini/commands
        cp -r "${GITHUB_ACTION_PATH}/.github/commands/"* .gemini/commands/
      env:
        GITHUB_ACTION_PATH: '${{ github.action_path }}'

    - name: 'Authenticate to Google Cloud'
      if: |-
        ${{ inputs.gcp_workload_identity_provider != '' }}
      id: 'auth'
      uses: 'google-github-actions/auth@v3' # ratchet:exclude
      with:
        project_id: '${{ inputs.gcp_project_id }}'
        workload_identity_provider: '${{ inputs.gcp_workload_identity_provider }}'
        service_account: '${{ inputs.gcp_service_account }}'
        token_format: '${{ inputs.gcp_token_format }}'
        access_token_scopes: '${{ inputs.gcp_access_token_scopes }}'

    - name: 'Install pnpm'
      if: |-
        ${{ inputs.use_pnpm == 'true' }}
      uses: 'pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061' # ratchet:pnpm/action-setup@v4
      with:
        version: 10

    - name: 'Install Gemini CLI'
      id: 'install'
      env:
        GEMINI_CLI_VERSION: '${{ inputs.gemini_cli_version }}'
        EXTENSIONS: '${{ inputs.extensions }}'
        USE_PNPM: '${{ inputs.use_pnpm }}'
      shell: 'bash'
      run: "$GITHUB_ACTION_PATH/scripts/install_gemini_cli.sh"

    - name: 'Run Gemini CLI'
      id: 'gemini_run'
      shell: 'bash'
      run: "$GITHUB_ACTION_PATH/scripts/run_gemini_cli.sh"
      env:
        GEMINI_DEBUG: '${{ fromJSON(inputs.gemini_debug || false) }}'
        GEMINI_API_KEY: '${{ inputs.gemini_api_key }}'
        SURFACE: 'GitHub'
        GOOGLE_CLOUD_PROJECT: '${{ inputs.gcp_project_id }}'
        GOOGLE_CLOUD_LOCATION: '${{ inputs.gcp_location }}'
        GOOGLE_GENAI_USE_VERTEXAI: '${{ inputs.use_vertex_ai }}'
        GOOGLE_API_KEY: '${{ inputs.google_api_key }}'
        GOOGLE_GENAI_USE_GCA: '${{ inputs.use_gemini_code_assist }}'
        GOOGLE_CLOUD_ACCESS_TOKEN: '${{steps.auth.outputs.access_token}}'
        PROMPT: '${{ inputs.prompt }}'
        GEMINI_MODEL: '${{ inputs.gemini_model }}'
        GH_WORKFLOW_NAME: '${{ steps.sanitize_workflow_name.outputs.gh_workflow_name }}'

    - name: 'Upload Gemini CLI outputs'
      if: |-
        ${{ inputs.upload_artifacts == 'true' }}
      uses: 'actions/upload-artifact@v6' # ratchet:exclude
      with:
        name: 'gemini-output'
        path: 'gemini-artifacts/'

    - name: 'Upload Telemetry to Google Cloud'
      if: |-
        ${{ inputs.gcp_workload_identity_provider != '' }}
      shell: 'bash'
      run: "$GITHUB_ACTION_PATH/scripts/upload_telemetry.sh"
      env:
        OTLP_GOOGLE_CLOUD_PROJECT: '${{ inputs.gcp_project_id }}'
        GITHUB_ACTION_PATH: '${{ github.action_path }}'
        GITHUB_REPOSITORY: '${{ github.repository }}'
        GITHUB_RUN_ID: '${{ github.run_id }}'

branding:
  icon: 'terminal'
  color: 'blue'
