name: Hello World Example

on:
  workflow_dispatch:

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run gemini-cli
        uses: ./
        with:
          prompt: "hello world"
