name: Deploy token exchange

on:
    workflow_dispatch:
      inputs:
        project_id:
          description: 'The GCP project ID where the token exchange service will be deployed.'
          required: true
          type: 'string'

jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                repository: abcxyz/github-token-minter
                ref: bff0776c3a11ddee36c5b9fc72299bd35994a075 # v2.3.2

            - uses: google-github-actions/auth@v2
              with:
                workload_identity_provider: projects/${{inputs.project_id}}/locations/global/workloadIdentityPools/ci-pipeline/providers/github-actions
                service_account: token-exchange-deployer@${{inputs.project_id}}.iam.gserviceaccount.com

            - id: deploy
              uses: 'google-github-actions/deploy-cloudrun@v2'
              with:
                service: github-token-exchange
                source: .

            - run: 'echo "Service deployed to ${{ steps.deploy.outputs.url }}"'
