---
name: 'Release'

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - 'main'
      - 'release/**/*'

permissions:
  contents: 'read'
  packages: 'write'

jobs:
  release:
    uses: 'google-github-actions/.github/.github/workflows/release.yml@v3'  # ratchet:exclude
    secrets:
      ACTIONS_BOT_TOKEN: '${{ secrets.ACTIONS_BOT_TOKEN }}'
