---
name: 'Test'

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - 'main'
      - 'release/**/*'
  pull_request:
    branches:
      - 'main'
      - 'release/**/*'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true  # yamllint disable-line rule:truthy

defaults:
  run:
    shell: 'bash'

permissions:
  contents: 'read'
  statuses: 'write'

jobs:
  yamllint:
    name: 'yamllint'
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # ratchet:actions/checkout@v4
      - name: Validate all YAML files
        run: |
          yamllint . --format github
