name: 'Test'

on:
  push:
    branches:
      - 'main'
      - 'release/**/*'
  pull_request:
    branches:
      - 'main'
      - 'release/**/*'
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

permissions:
  contents: 'read'
  statuses: 'write'

jobs:
  test:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # ratchet:actions/checkout@v4

      - name: 'Lint YAML'
        uses: 'abcxyz/actions/.github/actions/lint-yaml@48bf3573880bcd307661522345bbe419115c3d4b' # ratchet:abcxyz/actions/.github/actions/lint-yaml@main
        with:
          yamllint_url: 'https://raw.githubusercontent.com/google-github-actions/.github/main/.yamllint.yml'
